---
title: Reading Response 2
description: This is my submission for in-class #2
date: 2026-03-18
tags: 
---

# The Web’s Grain by Frank Chimero #

Like previous readings we covered, with this article I was yet again relieved to read something that really reflected aspects of technology and web development that I constantly think about; in this case, (the point I mostly took from it) how people in web design and development are starting to push websites past its technological barriers resulting in products and sites that feel unnecessarily overcomplicated and, in peoples’ pursuit of creating a product that is supposed to feel advanced, maybe futuristic, end up creating something that just feels unfun and hard to use (the Apple website was a great example). Knowing this article was written over a decade ago is really crazy because all of the points and worries that Chimero highlights throughout his writing are still very relevant today, if not, even more so now. With the introduction of AI, now people are able to create artwork, designs, and even full blown websites with no creative process (and honestly integrity) of their own, creating what I would consider a cesspool of dull, un-engaging, unoriginal websites and graphic designs. And like Chimero ends his article with, it really begs the question, what exactly is technology’s role in the individual’s everyday life? As a web developer, I find that this question is constantly on my mind as I try to create products that people would want to engage with, while also retaining my own creative freedom and what I’d consider the original technological frameworks of web dev and design without “yielding an incredibly fragile, willfully esoteric [product] that’s good for no one.”

# Heavy Lies the Digital Cloud by Emily Manges #

This article was kind of scary to me, funny. Particularly the line where Manges says “instead of scrolling through old texts, imagine a chatbot trained on your entire archive, answering back in your own voice.” That is an actually terrifying future to think about, and this reading was just a grim reminder of how pervasive the internet has become with the introduction and advancement of AI (this reminded me of that one episode from the latest season of Black Mirror titled “Eulogy,” where the main character is able to use a new piece of technology that allows him to look at old pictures and be back in those exact moments). Knowing the author of the article is also the founder of an “AI Wellness Platform” also explained their subtle tone of neutrality towards this “future” of AI and the Cloud holding all of our data, at least how I perceived it. While I can somewhat understand the author’s willfulness to accept a future of “different skies” in regards to making sure our personal internet usage archives are perhaps (in the future) utilized in a way that makes sure to map our complex and individualistic usages, I can not say I am as willful or curious to know.
